### ISSUE TITLE
Container returns an internal server error.

### ISSUE THREAD

**Issue by wibbene** [spacetimeengineer3/webfortune#3]
Going to guess there is an issue with app.py

**Comment by wibbene** [comment]
[2021-05-05 22:00:25,852] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app.py", line 35, in index
    return redirect(url_for('fortune'))
  File "/usr/local/lib/python3.6/dist-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'fortune'. Did you mean 'cowfortune' instead?
192.168.1.51 - - [05/May/2021 22:00:25] "GET / HTTP/1.1" 500 -
192.168.1.51 - - [05/May/2021 22:00:26] "GET /favicon.ico HTTP/1.1" 404 -
[2021-05-05 22:00:33,231] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app.py", line 35, in index
    return redirect(url_for('fortune'))
  File "/usr/local/lib/python3.6/dist-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'fortune'. Did you mean 'cowfortune' instead?
192.168.1.51 - - [05/May/2021 22:00:33] "GET / HTTP/1.1" 500 -
192.168.1.51 - - [05/May/2021 22:00:46] "GET /cowsay HTTP/1.1" 308 -
[2021-05-05 22:00:46,149] ERROR in app: Exception on /cowsay/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: cowsay() missing 1 required positional argument: 'text'
192.168.1.51 - - [05/May/2021 22:00:46] "GET /cowsay/ HTTP/1.1" 500 -

**Comment by wibbene** [comment]
alright Cowfortune works

/ ======================================= \
| ================================ || ||  |
| || The FORTUNE-COOKIE program is soon   |
| to be a Major Motion Picture! || ||     |
| Watch for it at a theater near you next |
| summer! || || ||                        |
| ======================================= |
| ================================        |
|                                         |
| Francis Ford Coppola presents a George  |
| Lucas Production:                       |
|                                         |
| "Fortune Cookie"                        |
|                                         |
| Directed by Steven Spielberg.           |
|                                         |
| Starring Harrison Ford Bette Midler     |
| Marlon Brando                           |
|                                         |
| Christopher Reeves Marilyn Chambers     |
|                                         |
| and Bob Hope as "The Waiter".           |
|                                         |
| Costumes Designed by Pierre Cardin.     |
|                                         |
| Special Effects by Timothy Leary.       |
|                                         |
| Read the Warner paperback!              |
|                                         |
| Invoke the Unix program!                |
|                                         |
| Soundtrack on XTC Records.              |
|                                         |
| In 70mm and Dolby Stereo at selected    |
| theaters and terminal                   |
|                                         |
\ centers.                                /
 -----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

**Comment by wibbene** [comment]
WORKS. this was a giant case of RTFM for flask.
